include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - sast
  - build-test
  - build-container

image:
  name: gcr.io/kaniko-project/executor:v1.9.1-debug
  entrypoint: [""]

variables:
  REGISTRY_NAME: docker.io

before_script:
  - echo "{\"auths\":{\"${REGISTRY_URL}\":{\"auth\":\"$(printf "%s:%s" "${REGISTRY_USER}" "${REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

sast:
  stage: sast
  before_script: []

semgrep-sast:
  stage: sast
  before_script: []
  allow_failure: true

# # Test if Containers are buildable
# file-web-test:
#   before_script: []
#   stage: build-test
#   script:
#     - |
#       /kaniko/executor \
#       --context $CI_PROJECT_DIR/src/webclient \
#       --dockerfile $CI_PROJECT_DIR/src/webclient/Dockerfile \
#       --no-push

# file-api-test:
#   before_script: []
#   stage: build-test
#   script:
#     - |
#       /kaniko/executor \
#       --context $CI_PROJECT_DIR/src/server \
#       --dockerfile $CI_PROJECT_DIR/src/server/Dockerfile \
#       --no-push

# file-cleaner-test:
#   before_script: []
#   stage: build-test
#   script:
#     - |
#       /kaniko/executor \
#       --context $CI_PROJECT_DIR/src/cleaner \
#       --dockerfile $CI_PROJECT_DIR/src/cleaner/Dockerfile \
#       --no-push

# Build and Push Containers
file-web:
  stage: build-container
  script: |
    /kaniko/executor \
    --context $CI_PROJECT_DIR/src/webclient \
    --dockerfile $CI_PROJECT_DIR/src/webclient/Dockerfile \
    --destination $REGISTRY_NAME/$REGISTRY_PROJECT/$CI_JOB_NAME:$CI_COMMIT_SHA
  only:
    changes:
      - "$CI_PROJECT_DIR/src/webclient"
    refs:
      - main

file-api:
  stage: build-container
  script: |
    /kaniko/executor \
    --context $CI_PROJECT_DIR/src/server \
    --dockerfile $CI_PROJECT_DIR/src/server/Dockerfile \
    --destination $REGISTRY_NAME/$REGISTRY_PROJECT/$CI_JOB_NAME:$CI_COMMIT_SHA
  only:
    changes:
      - "$CI_PROJECT_DIR/src/server"
    refs:
      - main

file-cleaner:
  stage: build-container
  script: |
    /kaniko/executor \
    --context $CI_PROJECT_DIR/src/cleaner \
    --dockerfile $CI_PROJECT_DIR/src/cleaner/Dockerfile \
    --destination $REGISTRY_NAME/$REGISTRY_PROJECT/$CI_JOB_NAME:$CI_COMMIT_SHA
  only:
    changes:
      - "$CI_PROJECT_DIR/src/cleaner"
    refs:
      - main
