include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - sast
  - build-container

image:
  name: gcr.io/kaniko-project/executor:v1.9.1-debug
  entrypoint: [""]

variables:
  REGISTRY_NAME: docker.io

before_script:
  - echo "{\"auths\":{\"${REGISTRY_URL}\":{\"auth\":\"$(printf "%s:%s" "${REGISTRY_USER}" "${REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

sast:
  stage: sast
  before_script: []

semgrep-sast:
  stage: sast
  before_script: []
  allow_failure: true

.build:
  stage: build-container
  only:
    refs:
      - main
      - tags

# Build and Push Containers
file-web:
  extends: .build
  script: |
    /kaniko/executor \
    --context $CI_PROJECT_DIR \
    --dockerfile $CI_PROJECT_DIR/src/docker/Dockerfile-web \
    --destination $REGISTRY_NAME/$REGISTRY_PROJECT/$CI_JOB_NAME:${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA} \
    --destination $REGISTRY_NAME/$REGISTRY_PROJECT/$CI_JOB_NAME:latest

file-api:
  extends: .build
  script: |
    /kaniko/executor \
    --context $CI_PROJECT_DIR \
    --dockerfile $CI_PROJECT_DIR/src/docker/Dockerfile-api \
    --destination $REGISTRY_NAME/$REGISTRY_PROJECT/$CI_JOB_NAME:${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA} \
    --destination $REGISTRY_NAME/$REGISTRY_PROJECT/$CI_JOB_NAME:latest

file-cleaner:
  extends: .build
  script: |
    /kaniko/executor \
    --context $CI_PROJECT_DIR \
    --dockerfile $CI_PROJECT_DIR/src/docker/Dockerfile-cleaner \
    --destination $REGISTRY_NAME/$REGISTRY_PROJECT/$CI_JOB_NAME:${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA} \
    --destination $REGISTRY_NAME/$REGISTRY_PROJECT/$CI_JOB_NAME:latest

file-migrations:
  extends: .build
  script: |
    /kaniko/executor \
    --context $CI_PROJECT_DIR \
    --dockerfile $CI_PROJECT_DIR/src/docker/Dockerfile-migrations \
    --destination $REGISTRY_NAME/$REGISTRY_PROJECT/$CI_JOB_NAME:${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA} \
    --destination $REGISTRY_NAME/$REGISTRY_PROJECT/$CI_JOB_NAME:latest
