version: '3.3'

volumes:
  files:
  pgdata:

networks:
  fdnet:
    name: fd_net

services:
  nginx:
    image: docker.io/nginx:1.22-alpine
    ports:
      - 8080:80
    volumes:
      - ./src/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web_service
      - file_drop
    networks:
      - fdnet

  postgres:
    image: docker.io/postgres:15.2-alpine
    environment:
      POSTGRES_PASSWORD:  "s3cr3t!"
      POSTGRES_USER:  "postgres"
      POSTGRES_DB:  "postgresdb"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/.psql-init-scripts/:/docker-entrypoint-initdb.d/
    restart: unless-stopped
    networks:
      - fdnet

  file_drop:
    image: docker.io/peek1e/file-api:latest
    environment:
      FD_DB_HOST: "postgres"
      FD_DB_USER: "postgres"
      FD_DB_NAME: "postgresdb"
      FD_DB_PASSWORD: "s3cr3t!"
    volumes:
      - files:/app/storage:rw,uid=10001,gid=10001
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - fdnet

  file_cleaner:
    image: docker.io/peek1e/file-cleaner:latest
    environment:
      FD_DB_HOST: "postgres"
      FD_DB_USER: "postgres"
      FD_DB_NAME: "postgresdb"
      FD_DB_PASSWORD: "s3cr3t!"
    volumes:
      - files:/app/storage:rw,uid=10001,gid=10001
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - fdnet
  
  web_service:
    image: docker.io/peek1e/file-web:latest
    restart: unless-stopped
    depends_on:
      - file_drop
    networks:
      - fdnet
