version: '3.3'
services:
  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_PASSWORD:  "password"
      POSTGRES_USER:  "postgres"
      POSTGRES_DB:  "uploads"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/.psql-init-scripts/:/docker-entrypoint-initdb.d/
    restart: unless-stopped

  file_drop:
    image: peek1e/file-api:latest
    build: ./src/server
    volumes:
      - files:/app/storage
    ports:
      - 8081:8080
    restart: unless-stopped
    depends_on:
      - db

  file_cleaner:
    image: peek1e/file-cleaner:latest
    build: ./src/cleaner
    volumes:
      - files:/app/storage
    restart: unless-stopped
    depends_on:
      - db
  
  web_service:
    image: peek1e/file-web:latest
    build: ./src/webclient
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - file_drop

volumes:
  files:
  pgdata:
