version: '3.3'

volumes:
  files:
  pgdata:

networks:
  fdnet:
    name: fd_net

services:
  postgres:
    image: docker.io/postgres:15.2-alpine
    environment:
      POSTGRES_PASSWORD:  "s3cr3t!"
      POSTGRES_USER:  "postgres"
      POSTGRES_DB:  "postgresdb"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/.psql-init-scripts/:/docker-entrypoint-initdb.d/
    restart: unless-stopped
    networks:
      - fdnet

  file_drop:
    image: docker.io/peek1e/file-api:dev
    volumes:
      - files:/app/storage
    ports:
      - 8081:8080
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - fdnet

  file_cleaner:
    image: peek1e/file-cleaner:dev
    volumes:
      - files:/app/storage
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - fdnet

  web_service:
    image: docker.io/peek1e/file-web:latest
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - file_drop
    networks:
      - fdnet
