version: '3.3'

volumes:
  files:
  pgdata:

services:
  postgres:
    image: docker.io/postgres:15.2-alpine
    network_mode: host
    environment:
      POSTGRES_PASSWORD:  "s3cr3t!"
      POSTGRES_USER:  "postgres"
      POSTGRES_DB:  "postgresdb"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  file_api:
    image: docker.io/peek1e/file-api:dev
    network_mode: host
    environment:
      FD_DB_HOST: "localhost"
      FD_DB_USER: "postgres"
      FD_DB_NAME: "postgresdb"
      FD_DB_PASSWORD: "s3cr3t!"
    tmpfs:
      - /app/storage
    restart: unless-stopped
    depends_on:
      - postgres
