version: '3.3'
services:
  db:
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD:  "CHANGE_ME"
      POSTGRES_USER:  "postgres"
      POSTGRES_DB:  "uploads"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/.psql-init-scripts/:/docker-entrypoint-initdb.d/
    restart: unless-stopped

  file_drop:
    image: peek1e/file-drop:latest
    build: ./src/server
    volumes:
     #- ./dbSettings.json:/app/db_settings/dbSettings.json
      - files:/app/storage #this may be configurable in the future
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - db

  file_cleaner:
    image: peek1e/file-cleaner:latest
    build: ./src/cleaner
    volumes:
     #- ./dbSettings.json:/app/db_settings/dbSettings.json
      - files:/app/storage #this may be configurable in the future
    restart: unless-stopped
    depends_on:
      - db
      - file_drop

volumes:
  files:
  pgdata:
