# download dependencies
FROM golang:1.20 AS base-build
WORKDIR /build
COPY [".", "./"]
RUN CGO_ENABLED=0 GOARCH=$TARGETARCH GOOS=linux go mod download

# build binary
FROM base-build AS build
WORKDIR /build
COPY . .
RUN CGO_ENABLED=0 GOARCH=$TARGETARCH GOOS=linux go build -o filedrop cmd/server/main.go

# new empty container
FROM scratch

USER 10001
WORKDIR /app

# Copy webcontent root
COPY --chown=10001:10001 src/webclient/pages/index.html /app/static/upload/index.html
COPY --chown=10001:10001 src/webclient/common /app/static/upload

# Copy webcontent decrypt
COPY --chown=10001:10001 src/webclient/pages/decryption.html /app/static/decrypt/index.html
COPY --chown=10001:10001 src/webclient/common /app/static/decrypt

# copy binary
COPY --chown=10001:10001 --from=build /build/filedrop /app/filedrop

EXPOSE "8080"
VOLUME /app/storage

ENTRYPOINT ["/app/filedrop"]
