# download dependencies
FROM golang:1.20 AS base-build
WORKDIR /build
COPY [".", "./"]
RUN CGO_ENABLED=0 GOARCH=$TARGETARCH GOOS=linux go mod download

# build binary
FROM base-build AS build
WORKDIR /build
COPY . .
RUN CGO_ENABLED=0 GOARCH=$TARGETARCH GOOS=linux go build -o cleaner cmd/cleaner/main.go

# new empty container
FROM scratch
USER 10001
WORKDIR /app
COPY --from=build /build/cleaner ./cleaner

ENTRYPOINT ["./cleaner"]
