# Default values for file-drop.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

#- Globals valid in every component
# the security contexts are preconfigured to work with the hardenend contaienr images
global:
  podAnnotations: {}
  podSecurityContext:
    fsGroup: 10001
  securityContext:
    capabilities:
      drop:
        - NET_RAW
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 10001

imagePullSecrets: []

serviceAccount:
  create: false

#- Secret holding environment Variables used by the API and Cleaner
# See https://gitlab.com/PeeK1e/file-drop#cli-flags-env-vars on what can be used
extraEnvSecretName: ""

#- Storage Config
persistence:
  # Must support ReadWriteMany
  storageClass: ""
  size: "50Gi"
  # overwrites other persistence settings
  existingClaimName: ""

#- Migrations settings
migrations:
  image:
    repository: "docker.io/peek1e/file-migrations"
    tag: ""
    pullPolicy: IfNotPresent
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

#- The API Service Component
# makes database calls and serves/accepts content
apiService:
  replicaCount: 2
  service:
    type: ClusterIP
    port: 8080
  image:
    repository: docker.io/peek1e/file-api
    tag: ""
    pullPolicy: IfNotPresent
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

cleanerService:
  replicaCount: 2
  image:
    repository: docker.io/peek1e/file-cleaner
    tag: ""
    pullPolicy: IfNotPresent
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

webService:
  replicaCount: 2
  service:
    type: ClusterIP
    port: 8080
  image:
    repository: docker.io/peek1e/file-web
    tag: ""
    pullPolicy: IfNotPresent
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

ingress:
  enabled: true
  className: "nginx"
  annotations:
    # kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: filedroptest.debian.testlab.cloudical.in
  tls:
    - secretName: chart-example-tls
      hosts:
        - filedroptest.debian.testlab.cloudical.in
