# Default values for file-drop.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

#- Secret holding environment Variables used by the API and Cleaner
# See https://gitlab.com/PeeK1e/file-drop#cli-flags-env-vars on what can be used
extraEnvSecretName: {}

#- The API Service Component
# makes database calls and serves/accepts content
apiService:
  replicaCount: 2
  service:
    type: ClusterIP
    port: 8080
  image:
    repository: docker.io/peek1e/file-api
    tag: "v{{ .Chart.appVersion }}"
    pullPolicy: IfNotPresent

  podAnnotations: {}
  podSecurityContext:
    {}
    # fsGroup: 2000
  securityContext:
    {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  nodeSelector: {}
  tolerations: []
  affinity: {}

cleanerService:
  replicaCount: 2
  service:
    type: ClusterIP
    port: 8080
  image:
    repository: docker.io/peek1e/file-cleaner
    tag: "v{{ .Chart.appVersion }}"
    pullPolicy: IfNotPresent
  podAnnotations: {}

  podSecurityContext:
    {}
    # fsGroup: 2000

  securityContext:
    {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  nodeSelector: {}

  tolerations: []

  affinity: {}

ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
