apiVersion: v1
kind: Service
metadata:
  name: {{ include "file-drop.name" . }}-api    networks:
      - fdnet
  labels:
    {{- include "file-drop.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiService.service.type }}
  ports:
    - port: {{ .Values.apiService.service.port }}
      targetPort: {{ .Values.apiService.service.port }}
      protocol: TCP
      name: http
  selector:
    component: api
    {{- include "file-drop.selectorLabels" . | nindent 4 }}
