apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "file-drop.name" . }}-cleaner
  labels:
    {{- include "file-drop.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.cleanerService.replicaCount }}
  selector:
    matchLabels:
      component: cleaner
      {{- include "file-drop.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.global.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        component: cleaner
        {{- include "file-drop.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: 10001
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.cleanerService.image.repository }}:{{ .Values.cleanerService.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.cleanerService.image.pullPolicy }}
          {{ if .Values.extraEnvSecretName }}
          envFrom:
            - secretRef:
                {{ if .Values.extraEnvSecret.create }}
                name: {{ .Values.extraEnvSecret.name | default $secretName }}
                {{ else }}
                name: {{ $secretName }}
                {{ end }}
          {{ end }}
          resources:
            {{- toYaml .Values.apiService.resources | nindent 12 }}
          securityContext:
            capabilities:
              drop:
                - NET_RAW
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
          volumeMounts:
          - name: data-dir
            mountPath: /app/storage
      volumes:
      - name: data-dir
        persistentVolumeClaim:
        {{ if .Values.persistence.existingClaimName }}
          claimName: {{ .Values.persistence.existingClaimName }}
        {{ else }}
          claimName: {{ include "file-drop.name" . }}
        {{ end }}
      {{- with .Values.cleanerService.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cleanerService.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cleanerService.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
