apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "file-drop.name" . }}-migrations
  labels:
    component: migrations
    {{- include "file-drop.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade, pre-install
    "helm.sh/hook-delete-policy": never
spec:
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
      containers:
        - name: pre-upgrade-job
          image: "{{ .Values.migrations.image.repository }}:{{ .Values.migrations.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.apiService.image.pullPolicy }}
          {{ if .Values.extraEnvSecretName }}
          envFrom:
          - secretRef:
              name: {{ .Values.extraEnvSecretName }}
          {{ end }}
          securityContext:
          {{- toYaml .Values.global.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.migrations.resources | nindent 12 }}
      restartPolicy: Never
      {{- with .Values.migrations.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migrations.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migrations.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}