{{ $name := (include "file-drop.name" .) }}
{{ $secretName := printf "%s-%s" $name "secret" }}
{{ $jobName := printf "%s-%s-%s" (include "file-drop.name" .) "migrations" (randAlphaNum 4 | lower) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobName }}
  labels:
    component: migrations
    {{- include "file-drop.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade, pre-install
    "helm.sh/hook-delete-policy": never
    "helm.sh/hook-weight": "1"
spec:
  template:
    metadata:
      {{- with .Values.global.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: 10001
      containers:
        - name: pre-upgrade-job
          image: "{{ .Values.migrations.image.repository }}:{{ .Values.migrations.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.apiService.image.pullPolicy }}
          envFrom:
          - secretRef:
              name: {{ default $secretName $.Values.extraEnvSecret.name }}
          securityContext:
            capabilities:
              drop:
                - NET_RAW
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
          resources:
            {{- toYaml .Values.migrations.resources | nindent 12 }}
      restartPolicy: Never
      {{- with .Values.migrations.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migrations.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migrations.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}