{{ if .Values.extraEnvSecret.create }}
{{ $namespace := $.Release.Namespace }}
{{ $secretName := $.Values.extraEnvSecret.database.secretName }}
{{ $userKey := $.Values.extraEnvSecret.database.usernameKey }}
{{ $pwKey := $.Values.extraEnvSecret.database.passwordKey }}
# get secret values
{{ $secret := (lookup "v1" "Secret" $namespace $secretName).data }}
{{ $user := "" }}
{{ $pw := "" }}
{{ range $i, $v := $secret }}
  {{ if eq $i $userKey }}
  {{ $user = ( $v | b64dec) }}
  {{ else if eq $i $pwKey }}
  {{ $pw = ( $v | b64dec) }}
  {{ end }}
{{ end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "file-drop.name" . }}-secret
  labels:
    {{- include "file-drop.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade, pre-install
    "helm.sh/hook-delete-policy": never
    "helm.sh/hook-weight": "0"
stringData:
    FD_DB_HOST: {{ $.Values.extraEnvSecret.database.hostName }}
    FD_DB_USER: {{ $user }}
    FD_DB_PASSWORD: {{ $pw }}
{{ end }}