{{ if .Values.extraEnvSecret.create }}
{{ $namespace := $.Release.Namespace }}
{{ $secretName := $.Values.extraEnvSecret.database.secretName }}
{{ $user := $.Values.extraEnvSecret.database.usernameKey }}
{{ $pw := $.Values.extraEnvSecret.database.passwordKey }}
{{ $secret := (lookup "v1" "Secret" $namespace $secretName).data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "file-drop.name" . }}-secret
  labels:
    {{- include "file-drop.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade, pre-install
    "helm.sh/hook-delete-policy": never
    "helm.sh/hook-weight": "0"
data:
    {{ range $i, $v := $secret}}
    "{{ $i }}": "{{ $v }}"
    {{ end }}
{{ end }}